# docker-compose.yml
version: '3'
services:

  #Postgres Database
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: api-integration-tests
    ports:
      - "5432:5432"
    networks:
      - testing-network
    volumes: 
      - ./db/:/docker-entrypoint-initdb.d/

    #GAP Find Open Data API
  gap-find-open-data-api:
    container_name: gap-find-open-data-api
    image: gap-find-open-data-api:latest
    depends_on:
      - postgres-db
    ports:
      - "8080:8086"
    environment:
      spring_datasource_url: jdbc:postgresql://postgres-db:5432/api-integration-tests
      spring_datasource_username: postgres
      spring_datasource_password: mysecretpassword
      jwt_secretKey: ${JWT_SECRET_KEY}
      user-service_domin: http://wiremock:8080
    networks:
      - testing-network

  #wiremock
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:2.35.0
    ports:
      - '8082:8080'
    volumes:
      - ./mockUserService/wiremock:/home/wiremock
    networks:
      - testing-network
    command:
      - "--global-response-templating"

networks:
  testing-network:
