# docker-compose.yml
version: '3'
services:

  #Postgres Database
  postgres-database:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gap-prototype
    ports:
      - "5432:5432"
    networks:
      - testing-network

  #GAP Find Open Data API
  api:
    container_name: gap-find-open-data-api
    image: gap-find-open-data-api:latest
    depends_on:
      - postgres-database
    ports:
      - "8080:8080"
    networks:
      - testing-network


  #Serenity Integration Tests
#  serenity:
#    container_name: serenity-prototype
#    image: maven:3.9.2-amazoncorretto-17
#    networks:
#      - testing-network

networks:
  testing-network: