# docker-compose.yml
version: '3'
services:

  #Postgres Database
  postgres-database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gap-prototype
    ports:
      - "5432:5432"
    networks:
      - testing-network

  #GAP Open API prototype
  prototype:
    image: gap-prototype:latest
    depends_on:
      - postgres-database
    ports:
      - "8080:8080"
    networks:
      - testing-network


  #Serenity Integration Tests

networks:
  testing-network: