# docker-compose.yml
version: '3'
services:

  #Postgres Database
  postgres-database:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: api-integration-tests
    ports:
      - "5432:5432"
    networks:
      - testing-network
    volumes: 
      - ./db/:/docker-entrypoint-initdb.d/

networks:
  testing-network:
