# docker-compose.yml
version: '3'
services:

  #Postgres Database
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: api-integration-tests
    ports:
      - "5432:5432"
    networks:
      - testing-network
    volumes: 
      - ./db/:/docker-entrypoint-initdb.d/

    #GAP Find Open Data API
  gap-find-open-data-api:
    container_name: gap-find-open-data-api
    image: gap-find-open-data-api:latest
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      spring_datasource_url: jdbc:postgresql://postgres-db:5432/api-integration-tests
      spring_datasource_username: postgres
      spring_datasource_password: mysecretpassword
      jwt_secretKey: ${JWT_SECRET_KEY}
    networks:
      - testing-network

networks:
  testing-network:
