# docker-compose.yml
version: '3'
services:

  #Postgres Database
  database:
    container_name: postgres-gap-prototype
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: gap-prototype
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  #GAP Open API prototype
  prototype:
    image: gap-prototype:latest
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - testing-network


  #Serenity Integration Tests

networks:
  testing-network:

volumes:
  db-data: