CREATE TABLE grant_scheme (
  grant_scheme_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   funder_id INTEGER NOT NULL,
   version INTEGER NOT NULL,
   created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
   created_by INTEGER NOT NULL,
   last_updated TIMESTAMP WITHOUT TIME ZONE,
   last_updated_by INTEGER,
   ggis_identifier VARCHAR(255) NOT NULL,
   scheme_name VARCHAR(255) NOT NULL,
   scheme_contact VARCHAR(255),
   CONSTRAINT pk_grant_scheme PRIMARY KEY (grant_scheme_id)
);


CREATE TABLE grant_applicant_organisation_profile (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   applicant_id BIGINT,
   legal_name VARCHAR(255),
   type VARCHAR(255),
   address_line1 VARCHAR(255),
   address_line2 VARCHAR(255),
   town VARCHAR(255),
   county VARCHAR(255),
   postcode VARCHAR(255),
   charity_commission_number VARCHAR(255),
   companies_house_number VARCHAR(255),
   CONSTRAINT pk_grant_applicant_organisation_profile PRIMARY KEY (id)
);

CREATE TABLE grant_applicant (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   user_id UUID,
   CONSTRAINT pk_grant_applicant PRIMARY KEY (id)
);

ALTER TABLE grant_applicant_organisation_profile ADD CONSTRAINT FK_GRANT_APPLICANT_ORGANISATION_PROFILE_ON_APPLICANT FOREIGN KEY (applicant_id) REFERENCES grant_applicant (id);

CREATE TABLE grant_application (
  grant_application_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   grant_scheme_id INTEGER,
   version INTEGER,
   created TIMESTAMP WITHOUT TIME ZONE,
   created_by INTEGER NOT NULL,
   last_updated TIMESTAMP WITHOUT TIME ZONE,
   last_update_by INTEGER,
   last_published TIMESTAMP WITHOUT TIME ZONE,
   application_name VARCHAR(255),
   status VARCHAR(255),
   definition JSON NOT NULL,
   CONSTRAINT pk_grant_application PRIMARY KEY (grant_application_id)
);

CREATE TABLE grant_submission (
  id UUID NOT NULL,
   applicant_id BIGINT,
   scheme_id INTEGER,
   application_id INTEGER,
   version INTEGER,
   created TIMESTAMP WITHOUT TIME ZONE,
   created_by BIGINT,
   last_updated TIMESTAMP WITHOUT TIME ZONE,
   last_updated_by BIGINT,
   submitted_date TIMESTAMP with time zone,
   application_name VARCHAR(255),
   status VARCHAR(255),
   definition JSON,
   gap_id VARCHAR(255),
   last_required_checks_export TIMESTAMP WITHOUT TIME ZONE,
   CONSTRAINT pk_grant_submission PRIMARY KEY (id)
);

ALTER TABLE grant_submission ADD CONSTRAINT FK_GRANT_SUBMISSION_ON_APPLICANT FOREIGN KEY (applicant_id) REFERENCES grant_applicant (id);

ALTER TABLE grant_submission ADD CONSTRAINT FK_GRANT_SUBMISSION_ON_APPLICATION FOREIGN KEY (application_id) REFERENCES grant_application (grant_application_id);

ALTER TABLE grant_submission ADD CONSTRAINT FK_GRANT_SUBMISSION_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES grant_applicant (id);

ALTER TABLE grant_submission ADD CONSTRAINT FK_GRANT_SUBMISSION_ON_LAST_UPDATED_BY FOREIGN KEY (last_updated_by) REFERENCES grant_applicant (id);

ALTER TABLE grant_submission ADD CONSTRAINT FK_GRANT_SUBMISSION_ON_SCHEME FOREIGN KEY (scheme_id) REFERENCES grant_scheme (grant_scheme_id);