name: Java CI with Maven

on:
  push:
    branches:
      - prototype/**
      - develop
      - main
  pull_request:
    branches:
      - prototype/**
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Serenity
        uses: actions/checkout@v3
        with:
          path: serenity
          repository: cabinetoffice/gap-serenity-bdd-prototype
          ref: main

      - name: Checkout Prototype
        uses: actions/checkout@v3
        with:
          path: prototype

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
#
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml -DskipTests
#
#      - name: Dependency check
#        uses: dependency-check/Dependency-Check_Action@main
#        env:
#          JAVA_HOME: /opt/jdk
#        id: DependencyCheck
#        with:
#          project: "gap-find-api-prototype"
#          path: "."
#          format: "HTML"
#          args: >
#            --enableRetired
#            --disableOssIndex true
#
#      - name: Upload dependency check report
#        uses: actions/upload-artifact@master
#        with:
#          name: DependencyCheck report
#          path: ${{github.workspace}}/reports
#
#      - name: Unit tests
#        run: mvn test
#      mvn spring-boot:build-image -DskipTests
#      docker compose -f docker-compose.yml up -d
#      docker compose down

      - name: setup integration test environment
        working-directory: ./prototype
        run: |
          ls -l $GITHUB_WORKSPACE
          echo ''
          echo ''
          pwd
          echo ''
          echo ''
          ls -l ../serenity/
          echo ''
          echo ''
          mvn spring-boot:build-image -DskipTests
          docker compose -f docker-compose.yml up -d
          docker cp ../serenity serenity-prototype:application
          docker exec -w /application serenity-prototype mvn clean verify
          docker logs serenity-prototype
          docker compose down