name: Java CI with Maven

env:
  JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
  JWT_TOKEN: ${{secrets.JWT_TOKEN}}

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API
        uses: actions/checkout@v3
        with:
          path: api

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        working-directory: ./api
        run: mvn -B package --file pom.xml -DskipTests

#      - name: Dependency check
#          uses: dependency-check/Dependency-Check_Action@main
#          env:
#            JAVA_HOME: /opt/jdk
#          id: DependencyCheck
#          with:
#            project: "gap-find-open-data-api"
#            path: "."
#            format: "HTML"
#            args: >
#              --enableRetired
#              --disableOssIndex true
#
#            - name: Upload dependency check report
#              uses: actions/upload-artifact@master
#              with:
#                name: DependencyCheck report
#                path: ${{github.workspace}}/reports
#
#            - name: Unit tests
#              working-directory: ./api
#              run: mvn test

      - name: Build Integration Environment
        working-directory: ./api
        run: |
          mvn spring-boot:build-image -DskipTests
          docker compose -f docker-compose-integration-tests.yml up -d
          sleep 30
          docker run --name newman-tests \
              -v /home/runner/work/gap-find-open-data-api/gap-find-open-data-api/api/postman:/opt/newman \
              --network gap-find-open-data-api_testing-network \
              postman/newman run /opt/newman/api.postman_collection.json \
              -e /opt/newman/Integration_Tests.postman_environment.json \
              --env-var "JWT_SECRET_KEY=${JWT_SECRET_KEY}" \
              --env-var "JWT_TOKEN=${JWT_TOKEN}"
