name: Java CI with Maven

on:
  push:
    branches:
      - prototype/**
      - develop
      - main
  pull_request:
    branches:
      - prototype/**
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: mysecretpassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

#      - name: DependencyCheck
#        uses: dependency-check/Dependency-Check_Action@main
#        env:
#          JAVA_HOME: /opt/jdk
#        id: DependencyCheck
#        with:
#          project: "gap-find-api-prototype"
#          path: "."
#          format: "HTML"
#          args: >
#            --enableRetired
#            --disableOssIndex true
#
#      - name: Upload Test results
#        uses: actions/upload-artifact@master
#        with:
#          name: DependencyCheck report
#          path: ${{github.workspace}}/reports

      - name: Integration tests
        run: |
          mvn spring-boot:build-image
          echo ''
          docker images
          echo ''
          docker run demo:0.0.1-SNAPSHOT -p 8080:8080 -n application
          echo '' 
          docker stop application