name: Promote to Prod Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

env:
  AWS_REGION: eu-west-2

jobs:
  promoteToProd:
    environment: AWS
    runs-on: ubuntu-latest
    permissions:
        id-token: write
        contents: read

    steps:
      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: gap-find-open-data-api-service
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Add prod tag to existing qa image
        # Based on steps described here - https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-retag.html
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name gap-find-open-data-api-service --image-ids imageTag=qa --output json | jq --raw-output --join-output '.images[0].imageManifest')
          aws ecr put-image --repository-name gap-find-open-data-api-service --image-tag prod --image-manifest "$MANIFEST"
